incident_title = input("What is the incident title ")
TR_Level = input("what is the TR level of the service ")
Users_affected = int(input("How many users are affected "))
Outage = input("are the users experiencing a full outage? ")
Production_affected = input("is production affected? ")
print("Incident variables", "\n", "incident title:", incident_title, "\n", "TR Level:", TR _Level, "\n", "Users_affected:", Users_affected, "\n", "Outage:", Outage, "\n", "Production affected:", Production_affected )
